TMH_proj/urls.py
from django.contrib import admin
from django.urls import path
from home import views
from django.conf.urls import include
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from home import views
app_name = 'home'
urlpatterns = [
path('', views.homepage, name='homepage'),
path('about/',views.about,name='about'),
path('register/',views.register,name='register'),
path('logout/',views.user_logout,name='user_logout'),
path('login/',views.user_login,name='user_login'),
path('restricted/',views.restricted,name='restrcited'),
path('edit_profile/',views.edit_profile,name='edit_profile'),
path('view_profile/',views.view_profile,name='view_profile'),
path('view_profile/change_password',views.change_password,name='change_password'),
path('<slug:category_name_slug>/',views.show_category,name='show_category'),
path('<slug:category_name_slug>/<slug:subcategory_name_slug>',views.show_sub,name='show_subcategory'),
path('<slug:category_name_slug>/<slug:subcategory_name_slug>/<slug:pet_name_slug>',views.show_pet,name='show_pet'),
path('<slug:category_name_slug>/<slug:subcategory_name_slug>/<slug:pet_name_slug>/add a pet',views.add_pet,name='add_pet'),





]

home/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class UserProfile(models.Model):
    # Take from here username, password, email, first:_name, last_name
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    address = models.CharField(max_length = 128)
    city = models.CharField(max_length = 20)
    postcode = models.CharField(max_length = 10)
    description = models.TextField(help_text = "Tell us something about you")
    picture = models.ImageField(upload_to='profile_images', default='media/profile_images/default-user.png')
    dob = models.DateField(null=True)
    isGiver = models.BooleanField(default = False)
    slug = models.SlugField(unique = True)
    date_reg = models.DateField(auto_now_add=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length = 128, unique = True)
    slug = models.SlugField(unique = True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
        
    class Meta:
        verbose_name_plural = "categories"
        
    def __str__(self):
        return self.name
class Subcategory(models.Model):
    name = models.CharField(max_length = 128, unique = True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    slug = models.SlugField(unique = True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Subcategory, self).save(*args, **kwargs)
        
    class Meta:
        verbose_name_plural = "subcategories"
        
    def __str__(self):
        return self.name


class Pet(models.Model):
    name = models.CharField(max_length = 128, help_text = "eg.cute cat")
    subcategory = models.ForeignKey(Subcategory, on_delete = models.CASCADE)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete = models.CASCADE)
    description = models.TextField(help_text = "Tell something about the pet")
    date = models.DateField(auto_now_add=True, blank=True, null=True)
    slug = models.SlugField(unique = True)
    
    image1 = models.ImageField(upload_to='pet_images', default='pet_images/default.png')
    
    def save(self, *args, **kwargs):
           self.slug = slugify(self.name)
           super(Pet, self).save(*args, **kwargs)
        
    class Meta:
        abstract = True
        
    def __str__(self):
        return self.name

class CurrentPet(Pet):
    image2 = models.ImageField(upload_to='pet_images', blank = True)
    image3 = models.ImageField(upload_to='pet_images', blank = True)
    image4 = models.ImageField(upload_to='pet_images', blank = True)
    image5 = models.ImageField(upload_to='pet_images', blank = True)
    owner = models.ForeignKey(UserProfile, on_delete = models.CASCADE, related_name="owner")
class Favorite(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    pets = models.ManyToManyField(CurrentPet)
class GivenPet(Pet):
    adopter = models.ForeignKey(UserProfile, on_delete=models.SET("This user no longer exists"), blank = False, related_name="adopter" )
    giver = models.ForeignKey(UserProfile, on_delete = models.CASCADE, related_name="given_by")

class Review(models.Model):
    title = models.CharField(max_length = 128, help_text = "Insert title here")
    text = models.TextField(help_text = "Tell us how the owner was")
    giver = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="reviewed")
    adopter = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="reviewer")
    on_date = models.DateField(auto_now_add=True, blank=True, null=True)
    rating = models.IntegerField(blank = False)
    def __str__(self):
        return self.title

home/forms.py
from django import forms
from home.models import Pet, UserProfile
from django.contrib.auth.models import User
import re


EMAIL_REGEX = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"

#Add product - not finished
class PetForm (forms.ModelForm):
    name = forms.CharField(max_length = 128, help_text="Please enter the name of the pet.")
    description = forms.CharField(help_text="Enter short description of the pet.")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model=Pet
        exclude=('subcategory',)


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    password2=forms.CharField(widget=forms.PasswordInput())

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if not password2:
            raise forms.ValidationError("You must confirm your password")
        if password != password2:
            raise forms.ValidationError("Your passwords do not match")
        return password

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and not re.match(EMAIL_REGEX, email):
            raise forms.ValidationError('Invalid email format')
        return email

    class Meta:
        model = User
        fields = ('first_name', 'last_name','username','email','password',)

class UserProfileForm(forms.ModelForm):
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = UserProfile
        fields = ('picture',)

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['city', 'postcode', 'description', 'picture','address']
    field_order=['address', 'postcode', 'city', 'description', 'picture']
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    

home/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from home.models import Category,Subcategory,CurrentPet,Pet
from home.forms import PetForm, UserForm, UserProfileForm,ProfileUpdateForm,UserUpdateForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse

def homepage(request):
    category_list = Category.objects.order_by('name')
    context_dict = {}
    context_dict['title'] = 'Welcome'
    context_dict['categories'] = {}
    for cat in category_list:
        context_dict['categories'][cat] = Subcategory.objects.filter(category=cat).order_by('name')
        
    response = render(request, 'home/homepage.html', context = context_dict)
    return response

def about(request):
    return render(request,'home/about.html')
def show_category(request,category_name_slug):
     context_dict = {}
     try:
         
         category_list = Category.objects.order_by('name')
         context_dict['categories'] = {}
    
         for cat in category_list:
             context_dict['categories'][cat] = Subcategory.objects.filter(category=cat).order_by('name')
        
         category_chosen = Category.objects.get(slug=category_name_slug)
         context_dict['chosen_category']=category_chosen

         pets=CurrentPet.objects.filter(category=category_chosen).order_by('date')
         context_dict['pet'] = pets
     except Category.DoesNotExist:
         context_dict['subcategory'] = None
         context_dict['category'] = None
     return render(request,'home/category.html',context=context_dict)
def show_sub(request,category_name_slug,subcategory_name_slug):
     context_dict = {}
     try:
         subcategory=Subcategory.objects.get(slug=subcategory_name_slug)
         pets=CurrentPet.objects.filter(subcategory=subcategory).order_by('date')
         context_dict['subcategory'] = subcategory
         context_dict['category'] = subcategory.category
         context_dict['pets'] = pets
     except Subcategory.DoesNotExist:
         context_dict['subcategory'] = None
         context_dict['category'] = None
         context_dict['pets'] = None
     return render(request,'home/subcategory.html',context=context_dict)
def show_pet(request,category_name_slug,subcategory_name_slug,pet_name_slug):
     context_dict = {}
     try:
         pet=Pet.objects.get(slug=pet_name_slug)
         context_dict['subcategory'] = pet.subcategory
         context_dict['category'] = pet.category
         context_dict['pets'] = pet
     except Subcategory.DoesNotExist:
         context_dict['subcategory'] = None
         context_dict['category'] = None
         context_dict['pets'] = None
     return render(request,'home/pet.html',context=context_dict)
@login_required
def add_pet(request, category_name_slug,subcategory_name_slug):
    
    try:
        subcategory = Subcategory.objects.get(slug=subcategory_name_slug)
    except:
        subcategory = None
    
    # You cannot add a page to a Category that does not exist... DM
    if subcategory is None:
        return redirect(reverse('home:homepage'))
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None
    if category is None:
        return redirect(reverse('home:homepage'))

    form = PetForm()

    if request.method == 'POST':
        form = PetForm(request.POST)

        if form.is_valid():
            if category:
                pet = form.save(commit=False)
                pet.category = category
                pet.subcategory=subcategory
                pet.owner = owner
                pet.save()

                return redirect(reverse('home:show_category', kwargs={'category_name_slug': category_name_slug,'subcategory_name_slug': subcategory_name_slug,'pet':pet,'added':added}))
        else:
            print(form.errors)  # This could be better done; for the purposes of TwD, this is fine. DM.
    
    context_dict = {'form': form, 'category': category,'subcategory_name_slug': subcategory_name_slug,'pet':pet,'added':added}
    return render(request, 'home/add_pet.html', context=context_dict)
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
            
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
        
    return render(request,'home/register.html',
    context = {'user_form': user_form,'profile_form': profile_form,
    'registered': registered})
@login_required
def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'home/profile.html', args)
@login_required
def edit_profile(request):
    context_dict = {}
    changed = False
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.userprofile)
        if form.is_valid() and profile_form.is_valid():
            user_form =form.save()
            custom_form = profile_form.save(commit=False)
            custom_form.user = user_form
            if 'picture' in request.FILES:
                custom_form.picture = request.FILES['picture']
            custom_form.save()
            messages.success(request, f'Your account has been updated!')
            changed = True

    else:
        form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
    
    context_dict['changed'] = changed
    context_dict ['form'] = form
    context_dict['profile_form'] = profile_form
    return render(request, 'home/edit_profile.html', context_dict)
def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return redirect (reverse ('home:homepage'))
            else:
                return HttpResponse("Your account is disabled")
        else:
            print(f"Invalid login details:{username}, {password}")
            return HttpResponse ("Invalid login details supplied.")
    else:
        return render(request, 'home/login.html')
        
@login_required
def user_logout(request):
     logout(request)
     return redirect(reverse('home:homepage'))

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('home:view_profile'))
        else:
            return redirect(reverse('home:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'home/change_password.html', args)
@login_required
def restricted(request):
    return render(request, 'home/restricted.html')

templates/home/about.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About TMH
{% endblock %}

{% block body_block %}
<div>
    The website has been put by<br />
	Hauwa<br />
	Elena<br />
</div>
{% endblock %}

templates/home/add_pet.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Pet
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a pet to {{ subcategory.name }}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post" action="{% url 'home:add_pet' category.slug subcategory.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">Add Pet</button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/home/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	 <head lang="en"> 
		<meta charset="UTF-8" /> 
		<title>
			TMH -
			{% block title_block %}  
			{% endblock %} 
		</title>
	</head>
	<body>
		<nav>
			
			
			{% if user.is_authenticated %} 
					<a href="{% url 'home:edit_profile' %}">Edit Profile</a>/
					<a href="{% url 'home:view_profile' %}">View Profile</a>/
					<a href="{% url 'home:change_password' %}">Change Password</a>/
					<a href="{% url 'home:user_logout' %}">Logout</a>

				{% else %} 
					<a href="{% url 'home:register' %}">Register</a>/
					<a href="{% url 'home:user_login' %}">Log in</a>/ 
				{% endif %} 
				<ul>
				    <li><a href="{% url 'home:about' %}">About</a></li>
                    <li><a href="{% url 'home:homepage' %}">Home</a></li>
                </ul>
			<hr />
		</nav>

		
		<div>
			{% block welcome_block %}
			<h1>Welcome to Take Me Home !</h1>
    		{% if user.is_authenticated %}
        			<h2>Hello, {{ user.username }}</h2>
   			 {% endif %}
   			 {% endblock %}
		</div>
		<div>
			{% block body_block %} 
				

			{% endblock %}
		</div>
		
		<div> 
			{% block sidebar_block %} 
			{% endblock %} 
		</div>


	</body>
</html>

templates/home/category.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

        {% block body_block %}

        {% if category %}
          <h1> {{ category.name }} </h1>
            <ul>
             {% if subcategories %} 
                <ul>
                {% for subcategory in subcategories %}
                <li><a href="/home/{{ category.slug }}/{{ subcategory.slug }}">{{ subcategory.name}}</li>
                 {% endfor %}
                </ul>
            {% endif %}
        {% endif %} 

         
        {% endblock %}
   

templates/home/change_password.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %} 
Change Password
{% endblock %}

{% block body_block %} 
	<h1>Change Password</h1> 
	<form id="change_password" method="post" action="{% url 'home:change_password' %}">
	  {% csrf_token %}
	  {{ form }}
	  <button type="submit">Save changes</button>
	</form> 
{% endblock %}

templates/home/edit_profile.html
{% extends 'home/base.html' %}

{% load staticfiles %}
{% block title_block %}
	Edit Profile
{% endblock %}

{% block body_block %}
	<h1>Edit Profile</h1>
	 
	 
	 
		<div >
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
       
        {{ form.as_p }}
        {{ profile_form.as_p }}
        
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

	{% endblock %}

templates/home/homepage.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block title_block %}
	Home
{% endblock %}



{% block body_block %} 

{% endblock %}


{% block sidebar_block %}            
<div>
{% if categories %}
            <ul>
            {% for category, subcategories in categories.items %}
                <h2><li><a href="/home/{{ category.slug }}/">{{ category.name }}</a></li></h2>
                {% if subcategories %}
                    <ul>
                        {% for subcategory in subcategories %}
                            <li><a href="/home/{{ category.slug }}/{{ subcategory.slug }}">{{ subcategory.name}}</li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no subcategories yet</strong>
                {% endif %}
            {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories yet</strong>
        {% endif %}
<div>
{% endblock %}

templates/home/login.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %} 
    Login 
{% endblock %}

{% block body_block %} 
<h1>Login to Take Me Home</h1> 
<form id="login_form" method="post" action="{% url 'home:user_login' %}"> 
	{% csrf_token %} 
	Username: <input type="text" name="username" value="" /> <br /> 
	Password: <input type="password" name="password" value="" /> <br /> 
	<input type="submit" value="submit" /> <br />
	
	

</form>
<p>
    Not registered?
    <a href="{% url 'home:register' %}">Register here!</a>
</p>

{% endblock %}

templates/home/pet.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ product.name }}
{% endblock %}

{% block body_block %}
 

    <h1>{{ pet.name }}</h1>
	<h1>{{ pet.description }}</h1>
    {% if pets %}
    <ul>
        {% for pet in products %}
		 <li><a href="/home/{{ category.slug }}/{{ subcategory.slug }}/{{pet.slug}}">{{ pet.name }}</a></li>
        <li><a><img src="{{pet.image1.url}}"></a>{{pet.image1}}</li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>This pet can not be adopted now</strong>
    {% endif %}
  
{% endblock %}

templates/home/profile.html
{% extends 'home/base.html' %}

{% load staticfiles %}

{% block title_block %}
    Profile
{% endblock %}

{% block body_block %}
<h1> Profile </h1>
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.description }}</p>
    <p>Phone: {{ user.phone }}</p>
    <p>City: {{ user.city }}</p>
    {% if user.picture %}
    <img src="{% media 'profile_images/default-user.png' alt='Picture of default user' /%}">
    {% endif %}
</div>

{% endblock %}

templates/home/register.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Register
{% endblock %}

{% block body_block %}
	<h1>Register for TMH!</h1>
	{% if registered %}
		<strong>Thank you for registering!</strong>
		<a href="{% url 'home:user_login' %}">Go to the Log in page.</a><br />
	{% else %}
		<strong>Register here!</strong><br />
		<form id="user_form" method="post" action="{% url 'home:register' %}" enctype="multipart/form-data">
	
			{% csrf_token %}
			{{ user_form.as_p }}
			{{ profile_form.as_p }}
			<input type="submit" name="submit" value="Register" />
		</form>
	{% endif %}
	{% endblock %}

templates/home/restricted.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %} 
Successful login
{% endblock %}

{% block body_block %}  
	<p> You have logged successfully.</p>
	<a href="{% url 'home:homepage' %}"> Return to homepage </a>

{% endblock %}

templates/home/subcategory.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Subcategoty
{% endblock %}

{% block body_block %}
    <head>
        <title>Subcategory</title>
    </head>

    <body>
    <body>
    <h1>{{ subcategory.name }}</h1>
	{% if user.is_authenticated %}
    <p> </p>
        {% if profile.isGiver %}
            <a href="/home/{{ category.slug }}/{{ subcategory.slug }}/add a pet /"><button type="button" class="btn btn-primary">Add a pet</button></a>
        {% endif %}
    {% endif %}
    {% if pets %}
    <ul>
        {% for pet in pets %}
        <li><a href="/home/{{ category.slug }}/{{ subcategory.slug }}/{{pet.slug}}">{{ pet.name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pets currently in this subcategory.</strong>
    {% endif %}
    </body>
{% endblock %}